name: Bump TOC Version

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Version bump type'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major
          - custom
      custom_version:
        description: 'Custom version (only used if version_type is custom)'
        required: false
        type: string
      create_changelog_entry:
        description: 'Create changelog entry'
        required: false
        default: true
        type: boolean
      create_release:
        description: 'Create release after version bump'
        required: false
        default: false
        type: boolean
      publish_to_curseforge:
        description: 'Publish release to CurseForge (only used if create_release is true)'
        required: false
        default: false
        type: boolean

permissions:
  contents: write
  actions: write

jobs:
  bump-version:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
        
    - name: Extract current version
      id: current_version
      run: |
        CURRENT_VERSION=$(grep "^## Version:" HealIQ.toc | cut -d' ' -f3)
        echo "current=$CURRENT_VERSION" >> $GITHUB_OUTPUT
        echo "Current version: $CURRENT_VERSION"
        
    - name: Calculate new version
      id: new_version
      run: |
        CURRENT="${{ steps.current_version.outputs.current }}"
        TYPE="${{ github.event.inputs.version_type }}"
        CUSTOM="${{ github.event.inputs.custom_version }}"
        
        # Validate current version format
        if [[ ! "$CURRENT" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "ERROR: Current version '$CURRENT' is not in semantic version format (x.y.z)"
          exit 1
        fi
        
        if [ "$TYPE" = "custom" ]; then
          if [ -z "$CUSTOM" ]; then
            echo "ERROR: Custom version not provided"
            exit 1
          fi
          
          # Validate custom version format
          if [[ ! "$CUSTOM" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "ERROR: Custom version '$CUSTOM' is not in semantic version format (x.y.z)"
            exit 1
          fi
          
          NEW_VERSION="$CUSTOM"
        else
          # Parse semantic version
          IFS='.' read -r major minor patch <<< "$CURRENT"
          
          # Validate parsed components are numbers
          if [[ ! "$major" =~ ^[0-9]+$ ]] || [[ ! "$minor" =~ ^[0-9]+$ ]] || [[ ! "$patch" =~ ^[0-9]+$ ]]; then
            echo "ERROR: Failed to parse version components from '$CURRENT'"
            exit 1
          fi
          
          case "$TYPE" in
            "major")
              major=$((major + 1))
              minor=0
              patch=0
              ;;
            "minor")
              minor=$((minor + 1))
              patch=0
              ;;
            "patch")
              patch=$((patch + 1))
              ;;
          esac
          
          NEW_VERSION="$major.$minor.$patch"
        fi
        
        echo "new=$NEW_VERSION" >> $GITHUB_OUTPUT
        echo "New version: $NEW_VERSION"
        
    - name: Check if version already exists
      id: check_version
      run: |
        NEW_VERSION="${{ steps.new_version.outputs.new }}"
        
        # Check if tag exists
        if git tag -l | grep -q "^v$NEW_VERSION$"; then
          echo "exists=true" >> $GITHUB_OUTPUT
          echo "ERROR: Version v$NEW_VERSION already exists as a git tag"
          exit 1
        fi
        
        # Check if version exists in changelog
        if grep -q "## \[$NEW_VERSION\]" CHANGELOG.md; then
          echo "changelog_exists=true" >> $GITHUB_OUTPUT
          echo "WARNING: Version $NEW_VERSION already exists in changelog"
        else
          echo "changelog_exists=false" >> $GITHUB_OUTPUT
        fi
        
        echo "exists=false" >> $GITHUB_OUTPUT
        echo "Version $NEW_VERSION is available"
        
    - name: Update TOC file
      run: |
        NEW_VERSION="${{ steps.new_version.outputs.new }}"
        
        # Backup original file
        cp HealIQ.toc HealIQ.toc.backup
        
        # Update version in HealIQ.toc
        sed -i "s/^## Version:.*/## Version: $NEW_VERSION/" HealIQ.toc
        
        # Verify the update worked
        UPDATED_VERSION=$(grep "^## Version:" HealIQ.toc | cut -d' ' -f3)
        if [ "$UPDATED_VERSION" != "$NEW_VERSION" ]; then
          echo "ERROR: Failed to update version in HealIQ.toc"
          echo "Expected: $NEW_VERSION"
          echo "Got: $UPDATED_VERSION"
          # Restore backup
          mv HealIQ.toc.backup HealIQ.toc
          exit 1
        fi
        
        # Remove backup
        rm HealIQ.toc.backup
        
        echo "Updated HealIQ.toc version to $NEW_VERSION"
        
    - name: Update Core.lua file
      run: |
        NEW_VERSION="${{ steps.new_version.outputs.new }}"
        
        # Backup original file
        cp Core.lua Core.lua.backup
        
        # Update version in Core.lua
        sed -i "s/HealIQ.version = \".*\"/HealIQ.version = \"$NEW_VERSION\"/" Core.lua
        
        # Verify the update worked
        UPDATED_VERSION=$(grep "HealIQ.version = " Core.lua | cut -d'"' -f2)
        if [ "$UPDATED_VERSION" != "$NEW_VERSION" ]; then
          echo "ERROR: Failed to update version in Core.lua"
          echo "Expected: $NEW_VERSION"
          echo "Got: $UPDATED_VERSION"
          # Restore backup
          mv Core.lua.backup Core.lua
          exit 1
        fi
        
        # Remove backup
        rm Core.lua.backup
        
        echo "Updated Core.lua version to $NEW_VERSION"
    - name: Create changelog entry
      if: ${{ github.event.inputs.create_changelog_entry == 'true' && steps.check_version.outputs.changelog_exists == 'false' }}
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        NEW_VERSION="${{ steps.new_version.outputs.new }}"
        
        echo "Generating enhanced changelog entry with AI WoW flair for version $NEW_VERSION..."
        
        # Install GitHub models extension for AI functionality
        echo "Installing GitHub models extension for AI enhancement..."
        gh extension install github/gh-models || echo "Failed to install models extension, AI enhancement may not work"
        
        # Make sure the enhanced changelog script is executable
        chmod +x .github/scripts/generate-changelog-enhanced.sh
        chmod +x .github/scripts/enhance-changelog-with-wow-flair.sh
        
        # Get the previous version tag
        PREV_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
        
        if [ -z "$PREV_TAG" ]; then
          echo "No previous tag found, generating enhanced changelog from initial commit..."
          ./.github/scripts/generate-changelog-enhanced.sh initial $NEW_VERSION
        else
          echo "Generating enhanced changelog from $PREV_TAG to $NEW_VERSION..."
          ./.github/scripts/generate-changelog-enhanced.sh $PREV_TAG $NEW_VERSION
        fi
        
        echo "Enhanced changelog entry created for version $NEW_VERSION with AI WoW flair"
        
    - name: Validate version consistency
      run: |
        NEW_VERSION="${{ steps.new_version.outputs.new }}"
        
        # Extract versions from both files
        TOC_VERSION=$(grep "^## Version:" HealIQ.toc | cut -d' ' -f3)
        CORE_VERSION=$(grep "HealIQ.version = " Core.lua | cut -d'"' -f2)
        
        echo "Validating version consistency..."
        echo "TOC version: $TOC_VERSION"
        echo "Core.lua version: $CORE_VERSION"
        echo "Expected version: $NEW_VERSION"
        
        # Check both files have the correct version
        if [ "$TOC_VERSION" != "$NEW_VERSION" ]; then
          echo "ERROR: HealIQ.toc version ($TOC_VERSION) does not match expected version ($NEW_VERSION)"
          exit 1
        fi
        
        if [ "$CORE_VERSION" != "$NEW_VERSION" ]; then
          echo "ERROR: Core.lua version ($CORE_VERSION) does not match expected version ($NEW_VERSION)"
          exit 1
        fi
        
        # Check both files have the same version
        if [ "$TOC_VERSION" != "$CORE_VERSION" ]; then
          echo "ERROR: Version mismatch between HealIQ.toc ($TOC_VERSION) and Core.lua ($CORE_VERSION)"
          exit 1
        fi
        
        echo "Version consistency validation passed!"
        
    - name: Commit changes
      run: |
        NEW_VERSION="${{ steps.new_version.outputs.new }}"
        CURRENT_VERSION="${{ steps.current_version.outputs.current }}"
        
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        git add HealIQ.toc Core.lua
        
        # Add changelog if it was updated
        if [ "${{ github.event.inputs.create_changelog_entry }}" = "true" ] && [ "${{ steps.check_version.outputs.changelog_exists }}" = "false" ]; then
          git add CHANGELOG.md
        fi
        
        git commit -m "Bump version from $CURRENT_VERSION to $NEW_VERSION"
        
        echo "Committed version bump changes"
        
    - name: Push changes
      run: |
        git push origin ${{ github.ref_name }}
        echo "Pushed version bump to ${{ github.ref_name }}"
        
    - name: Trigger release workflow
      if: ${{ github.event.inputs.create_release == 'true' }}
      id: trigger_release
      uses: actions/github-script@v8
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          try {
            const result = await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'release.yml',
              ref: '${{ github.ref_name }}',
              inputs: {
                publish_to_curseforge: '${{ github.event.inputs.publish_to_curseforge }}'
              }
            });
            console.log('Release workflow triggered successfully');
            return 'success';
          } catch (error) {
            console.error('Failed to trigger release workflow:', error.message);
            if (error.message.includes('Resource not accessible by integration')) {
              console.error('This error typically indicates insufficient permissions. Ensure the workflow has "actions: write" permission.');
            }
            return 'failed';
          }
        
    - name: Summary
      if: always()
      run: |
        NEW_VERSION="${{ steps.new_version.outputs.new }}"
        CURRENT_VERSION="${{ steps.current_version.outputs.current }}"
        
        echo "## Version Bump Summary" >> $GITHUB_STEP_SUMMARY
        echo "- Previous version: $CURRENT_VERSION" >> $GITHUB_STEP_SUMMARY
        echo "- New version: $NEW_VERSION" >> $GITHUB_STEP_SUMMARY
        echo "- Bump type: ${{ github.event.inputs.version_type }}" >> $GITHUB_STEP_SUMMARY
        echo "- Changelog entry created: ${{ github.event.inputs.create_changelog_entry }}" >> $GITHUB_STEP_SUMMARY
        echo "- Auto-release enabled: ${{ github.event.inputs.create_release }}" >> $GITHUB_STEP_SUMMARY
        echo "- Publish to CurseForge: ${{ github.event.inputs.publish_to_curseforge }}" >> $GITHUB_STEP_SUMMARY
        echo "- Branch: ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        if [ "${{ github.event.inputs.create_release }}" = "true" ]; then
          if [ "${{ steps.trigger_release.outcome }}" = "success" ]; then
            echo "The release workflow has been successfully triggered and will create a new release." >> $GITHUB_STEP_SUMMARY
          else
            echo "Attempted to trigger the release workflow, but it may have failed. Please check the workflow logs or manually trigger a release." >> $GITHUB_STEP_SUMMARY
          fi
        else
          echo "The release workflow will automatically create a new release when these changes are merged to main." >> $GITHUB_STEP_SUMMARY
        fi
